DOMAIN=
AUTH_EMAIL=
AUTH_TOKEN=

SCOPE_JQL=project = {YOUR_PROJECT_NAME}
#YYYY-MM-DD
FROM_DATE=2025-01-01
TO_DATE=2026-02-01

PARALLEL=8
MAX_RESULTS=100

# List users
USERS=a@company.com,b@company.com

# Or like this
# USER=a@company.com
# USER=b@company.com
