# Required
DOMAIN=
AUTH_EMAIL=
API_TOKEN=

SCOPE_JQL=project = {YOUR_PROJECT_NAME}

FROM=2025-01-01
TO=2026-02-01



# List users
USERS=user1@company.com;user2@company.com

# Or like this
# USER=user1@company.com
# USER=user2@company.com
